### ISSUE TITLE
What's up with this? 

### ISSUE THREAD

**Issue by nitinthewiz** [driftyco/collide#6]
Collide.io is down, the test.html file doesn't seem to work when downloaded as a zip file. Is this project going anywhere?

**Comment by mlynch** [comment]
It's in active use in our tinder cards ion:
https://github.com/driftyco/ionic-ion-tinder-cards

But the project itself is a bit on the back burner. That being said, it
works pretty darn well for spring and gravity animations, so give it a try!

On Sun, Mar 8, 2015 at 9:23 PM, Nitin Khanna <notifications@github.com>
wrote:

> Collide.io is down, the test.html file doesn't seem to work when
> downloaded as a zip file. Is this project going anywhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/collide/issues/6>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by nitinthewiz** [comment]
Ah, very well... I've seen the Tinder Cards app. Pretty good animation!
